### ISSUE TITLE
OpenSSL::Cipher::CipherError "key length too short"

### ISSUE THREAD

**Issue by odigity** [cvonkleist/encrypted_cookie#10]
I just tried this gem for the first time and immediately hit that error.  (I was using 'secret' as my session secret as I'm merely in development.)  Making it longer fixed the problem (minimum: 16 chars, or 128 bits).  Opening this issue in case other people experience the same problem so there's a chance they'll find it.

BTW - It reported the error on line 94 of encrypted_cookie.rb, and while trying to find the reference code, I noticed that this gem has changed immensely since it's last release (0.0.4 in March 2013).  Would be nice if someone pushed out a 0.0.5.

**Comment by odigity** [comment]
I just pulled in the latest version of the code directly from GitHub in place of 0.0.4:

# Gemfile
gem 'encrypted_cookie', github: 'cvonkleist/encrypted_cookie'

The latest version does not freak out with a short key.  Sure would be nice to get a version bump.  :)

BTW-I also noticed the session cookie doesn't have httponly set to true.  Granted, this is not very important when the cookie is encrypted, but given the option, I'd rather have it set to true.  Luckily, the latest version of the RDoc demonstrates that Rack::Session::EncryptedCookie takes the same options as Rack::Session::Cookie.  And once a new version is released, people visiting https://rubydoc.info/gem/encrypted_cookie/ will know that, too.  :)

**Comment by mkristian** [comment]
so basically your issue to have a 0.0.5 release.

+1 for it from my side :)

**Comment by ckuttruff** [comment]
just bumping this... ran into this as well.  Thanks!

**Comment by bettingweekly** [comment]
If people are still having issues with this as some of the other thread are unclear.

If you have a 16 bit key for example and you require a 32 bit key as OpenSSL cipher says you need.

You can do the following

cipher.key = Digest::SHA1.hexdigest("YOUR 16BIT SECRET KEY").slice(0, 32)

**Comment by namelessjon** [comment]
This should now be resolved
