### ISSUE TITLE
Bump version on RubyGems?

### ISSUE THREAD

**Issue by mikeknep** [cvonkleist/encrypted_cookie#14]
Hi there,
Could you bump the version of this gem and publish the latest to rubygems? The most recent version there is from 2011... Would be much appreciated!

**Comment by flexaddicted** [comment]
Hello,

Any update on this? Thank you!

**Comment by cvonkleist** [comment]
Sorry, guys, I am so behind on this! 😭 I will get the version bumped on RubyGems this week.

**Comment by stmllr** [comment]
@cvonkleist  Thank you for actively maintaining your gem. It brings value to people!

**Comment by flexaddicted** [comment]
Thank you :)

**Comment by stmllr** [comment]
The release on RubyGems works. Thanks! I guess this issue can be closed
